INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 17);
