INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 17);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 20);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 17);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 20);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 20);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 17);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 15);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 20);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 15);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 17);
