INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(166, 7,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(231,45,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 70,42,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(192,44,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(251,25,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(102,52,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(110,44,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(103,34,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 23,11,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(146,30,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(123,50,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(188,43,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(125,23,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 26, 3,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(164,17,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(101,48,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(159,60,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(240,17,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 68,38,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(133,38,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 73, 6,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(191, 8,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(294,35,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(274,26,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(171,20,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(242, 3,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 70,35,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(198,48,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(191,50,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 79,24,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(162,54,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(150,29,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(114, 1,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 88,15,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 17,37,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(230,20,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(148,56,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 67,33,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(130,57,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(273,50,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(169,43,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(121,13,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(287,17,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(201,29,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(155,42,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(110,40,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(126,22,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(210,21,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 73, 9,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 19, 7,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 16, 9,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(127,20,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(246,11,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(300,44,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(278,42,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 38,41,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(120,25,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 27,11,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(300, 6,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(269, 4,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(289,34,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(149,53,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 89,17,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 95, 6,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(173,25,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 75,26,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 23,26,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(235,19,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 94,18,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(263,41,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(285, 3,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(147,20,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(113,20,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(201,30,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(115,40,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(113,55,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(138,27,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(120,19,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(123, 8,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(293, 1,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(197,30,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(187,16,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(147,13,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 58,18,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(157,60,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(  7,41,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(172,60,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 57,31,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(247,46,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(139,25,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 67,52,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 20,15,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(151,42,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 45,22,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(  1,27,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(143, 4,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(215,41,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(155,15,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(109,28,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 13,60,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(198,13,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 94, 9,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 85,28,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 39, 6,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(141,52,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(165,14,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(112,10,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(139,40,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(214,42,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(158,23,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(178,42,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 71, 6,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(257,40,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(130,54,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 53,20,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(213,25,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 43,54,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(125,21,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 77,10,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 69,18,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 48, 1,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(203,23,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(184,36,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(285,43,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(227,33,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(211,26,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(185,48,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(275,16,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(121,31,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(278, 3,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(270,20,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(159,53,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(108,37,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(278,35,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(275,16,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 93,41,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(185,31,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(154, 4,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(295,10,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 70,49,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 68,43,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(167,46,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(121,36,0,1,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(166,27,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 37,52,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 41,31,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 49,22,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(198,55,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(229,60,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(179,51,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(121,29,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(250,53,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 84,46,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(168,25,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 49, 1,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(280, 9,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(299,24,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(152, 6,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(184, 5,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(278,20,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(191,41,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(233, 6,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 38,36,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(151,10,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(139,55,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(192,46,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(235,23,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 57,37,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 24,12,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(200, 1,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(172,54,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(240, 4,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 28,54,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 50,44,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 31,60,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(210,24,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 29,44,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 15,22,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(220,25,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(112,55,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 90,54,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(123,10,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(182,37,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(234, 8,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(286,42,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 60,27,0,2,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(  9,24,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(201,43,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 48,29,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 37,30,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(144,59,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(158,10,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 61,55,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 44,49,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(262,24,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(155,35,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(256, 3,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(254,20,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(294,31,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(191, 3,0,2,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 98, 5,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(133,34,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(208,11,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 97,50,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 66,13,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(184,23,0,1,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(227,33,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(296,45,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 96,59,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(276,46,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(246,22,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(209,23,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(177,28,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(269,51,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 34,30,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 73,53,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 87,12,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(103, 3,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(279,10,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(  8, 2,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(247,33,0,1,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(275, 6,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(245,41,0,2,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(142, 1,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(177,55,0,1,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(243,13,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 54,16,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 90,11,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 92, 5,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 60, 1,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 98,53,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(240,30,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(175, 6,0,3,'przelew tradycyjny');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 70,59,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(175,45,0,2,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(133,16,0,2,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(129,14,0,1,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(196,31,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(199,45,0,3,'karta');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 89,24,0,3,'voucher');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(263,37,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(282, 6,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(225,54,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(172, 8,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES( 76,29,0,3,'paypal');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(137,16,0,2,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(282,49,0,3,'przelew internetowy');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(242,54,0,3,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(174,10,0,1,'gotowka');
INSERT INTO zamowienia(klient_id, wycieczka_id, wartosc_zamowienia, klasa_oferty, sposob_platnosci) VALUES(153, 3,0,1,'paypal');
